### ISSUE TITLE
双屏显示

### ISSUE THREAD

**Issue by simmongu** [idxdy/asrock_b360m_itxac#1]
请问下你的EFI HDMI可以正常输出与DP组双屏吗

**Comment by idxdy** [comment]
我平时工作就是HDMI+DP组的双屏，2个都是2k的屏幕，但是双屏有个不影响使用小问题，
- 开机的话HDMI的那个屏幕会有一点撕裂感，但是一会儿就没了， 单个不管是HDMI还是DP都没有
- 唤醒的时候没有单个的快

**Comment by simmongu** [comment]
我的主板用的b365itx，接口怎么看跟b360itx差不多的，但是我就只能DP输出，hdmi就是输出不了

**Comment by idxdy** [comment]
这个我就不知道呢, 可能是index对不上吧, 你找对应的365的efi呗

simmongu <notifications@github.com> 于2020年3月18日周三 下午2:04写道：

**Comment by simmongu** [comment]
终于解决了并不是index不对，是总线id不对，这个id组合真的是要一个个试过来的。。
