### ISSUE TITLE
选择OC启动没有选项

### ISSUE THREAD

**Issue by caile19920926** [idxdy/asrock_b360m_itxac#3]
用这个OC的EFI启动，没有选项，我用CLOVER装好了之后再选择OC启动就默认直接启动了，中间过程没有选项

**Comment by idxdy** [comment]
> 用这个OC的EFI启动，没有选项，我用CLOVER装好了之后再选择OC启动就默认直接启动了，中间过程没有选项

因为我不需要其它的选项，如果你需要的话，直接看文档配，或者参考我文档里面的分区方式

**Comment by caile19920926** [comment]
选择OC安装的时候直接重启了，始终无法进入安装，是BIOS问题么？

**Comment by idxdy** [comment]
> 选择OC安装的时候直接重启了，始终无法进入安装，是BIOS问题么？

这个我不清楚的哦，你对照我的文档的bios设置试下呢

**Comment by caile19920926** [comment]
我设置了，就最后一项OS，不知道在哪，我没找到

**Comment by caile19920926** [comment]
我用黑果小兵的clover引导安装，进入系统后把efi替换成你的oc efi就成功了，现在开机能直接进入，谢谢你的efi
