### ISSUE TITLE
我用这个EFI每次选择完OC启动后就直接重启了，百思不得其解！

### ISSUE THREAD

**Issue by jickyx** [idxdy/asrock_b360m_itxac#6]
我用这个EFI每次选择完OC启动后就直接重启了，无法进入OC引导界面，这个是怎么回事呢？百思不得其解！

我和你的区别就是我有独显 蓝宝石RX570 和 网卡不是DW1820a

**Comment by idxdy** [comment]
其实还有个差异就是我选择的型号是macmini8,1, 而macmini是无显卡的, 可以尝试把显卡断开, 然后启动, 试下, 等电脑启动了再操作其他的
